### ISSUE TITLE
削除した後に追加しようとすると、重複判定される

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-server#3]
## 概要

GB11514を削除（メモなどもある状態）
↓
GB11514を追加
↓
500 error(重複しています)

![image](https://user-images.githubusercontent.com/39324739/70412384-0f2a4100-1a98-11ea-9acf-255362866c20.png)

## 備考

https://dev.api.twinte.net/v1/timetables

からは消えている

**Comment by SIY1121** [comment]
これ、Periodは消しても、ユーザー講義は消えないから起こるんだけど、
- 最後のコマが削除されたらユーザー講義も削除
- 削除用のAPIを叩くようにする
のどっちが美しいかなぁ...

**Comment by SIY1121** [comment]
restful api 的に考えれば後者（前者は副作用があるので）

**Comment by HikaruEgashira** [comment]
restfulにすべきかと

**Comment by SIY1121** [comment]
生やしました

**Comment by HikaruEgashira** [comment]
おっけーです。こっちも対応します
