### ISSUE TITLE
4/27-4/30までの授業情報が表示されない

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-server#30]
**バグの説明**
簡潔にバグを説明してください。
ウィジェットで2020年度の4/27-4/30までの授業情報が表示されない。

**再現手順**
バグを再現するための手順:
1.春Aの授業を登録する
2.ウィジェットで確認すると4月いっぱいは一切表示されない。5月以降は問題なし。

**期待される挙動**
4/27-4/30は通常通り授業が表示されて欲しい

**スクリーンショットやログ**

**環境**
 - OS: Android iOS 直接APIを叩いても確認
 - Browser:
 - Version:

**その他**

**Comment by SIY1121** [comment]
フロントと同じミスしてた（）
