### ISSUE TITLE
レスポンスの型修正

### ISSUE THREAD

**Issue by HikaruEgashira** [twin-te/twinte-server#55]
**バグの説明**
簡潔にバグを説明してください。
https://api.twinte.net/api-docs/#/%E8%AC%9B%E7%BE%A9%E6%83%85%E5%A0%B1/LectureServiceLectureFromKeyword
のswaggerのレスポンスの型がUserLectureEntityになってる
プロダクトに影響はない

**再現手順**
バグを再現するための手順:
1.https://api.twinte.net/api-docs/#/%E8%AC%9B%E7%BE%A9%E6%83%85%E5%A0%B1/LectureServiceLectureFromKeyword
2.try it out
3.ドキュメントの レスポンスとちょっと違う
...

**期待される挙動**
本来どのような挙動になるべきか説明してください。
返される型がなんか古い`lectureCode`とかもきになるので`lecture_code`に統一
UserLectureEntityではないはず

**スクリーンショットやログ**
![Screen Capture_select-area_20201019130349](https://user-images.githubusercontent.com/39324739/96400395-8ded2000-120b-11eb-8f72-b14c83525a86.png)

**環境**
10/19 https://api.twinte.net/api-docs

**その他**
補足説明等あれば書いてください。
swaggerからapi自動生成したいので修正したい

**Comment by SIY1121** [comment]
これ今更ながら 講義検索の返り値に限っては `lecture_code` じゃなくて `lectureCode` になってるな（）
修正できるけどどうする？（本番反映のタイミングは考える必要あるけど）

**Comment by HikaruEgashira** [comment]
`lecture_code`に統一したい
11月始まるくらいに本番反映する感じで

**Comment by HikaruEgashira** [comment]
フロントも`lecture_code`にします
（検索部分は治ってなかった）

**Comment by SIY1121** [comment]
`lecutre_code`化は別PR建てるね
